import {
    SiJavascript,
    SiHtml5,
    SiTypescript,
    SiCss3,
    SiReact,
    SiRedux,
    SiReactrouter,
    SiWebpack,
    SiEslint,
    SiJest,
    SiStorybook,
    SiBootstrap,
    SiVisualstudiocode,
    SiGithub,
    SiFigma,
    SiAdobephotoshop,
    SiMui,
} from "react-icons/si";
import { TbApi, TbDevices } from "react-icons/tb";

export const skills = [
    { name: "JavaScript", icon: <SiJavascript /> },
    { name: "HTML5", icon: <SiHtml5 /> },
    { name: "TypeScript", icon: <SiTypescript /> },
    { name: "CSS", icon: <SiCss3 /> },
    { name: "React", icon: <SiReact /> },
    { name: "Redux", icon: <SiRedux /> },
    { name: "Router", icon: <SiReactrouter /> },
    { name: "Webpack", icon: <SiWebpack /> },
    { name: "Eslint", icon: <SiEslint /> },
    { name: "Jest", icon: <SiJest /> },
    { name: "Storybook", icon: <SiStorybook /> },
    { name: "Bootstrap", icon: <SiBootstrap /> },
    { name: "VS Code", icon: <SiVisualstudiocode /> },
    { name: "Github", icon: <SiGithub /> },
    { name: "Figma", icon: <SiFigma /> },
    { name: "Photoshop", icon: <SiAdobephotoshop /> },
    { name: "Api", icon: <TbApi /> },
    { name: "Responsive Websites", icon: <TbDevices /> },
    { name: "Mui", icon: <SiMui /> },
];
